config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :my_swaps, to: 'pages#my_swaps'

  get :my_bookclub, to: 'pages#my_bookclub'


  get :my_books, to: 'pages#my_books'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: %i[index show new create destroy] do
    resources :swaps, only: %i[new create]
    member do
      get :genre
      get :confirmation
    end
  end
  resources :swaps, only: %i[show destroy] do
    member do
      get :chatroom
      get :choose_book
      patch :book_chosen
      patch :reject
      patch :complete
    end
    resources :messages, only: :create
  end
  resources :bookclubs, only: %i[index show] do
    get :confirmation
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="social-links-div">
    <a href="https://www.instagram.com/juntobookclub/" class="social-link fab fa-instagram">
    </a>
    <a href="https://www.facebook.com/groups/1715381925391873/" class="social-link fab fa-facebook-f">
    </a>
        <a href="https://twitter.com/TwitterBooks?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" class="social-link fab fa-twitter">
    </a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active-nav">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Find a Book Club", bookclubs_path, class: "nav-link btn-salmon" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "default-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Swaps", my_swaps_path, class: "dropdown-item" %>
            <% if current_user.bookclub %>
              <%= link_to "My Book Club", bookclub_path(current_user.bookclub), class: "dropdown-item" %>
            <% end %>

            <%= link_to "My Books", my_books_path, class: "dropdown-item" %>

            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link btn-salmon" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>