config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :my_swaps, to: 'pages#my_swaps'

  get :my_bookclub, to: 'pages#my_bookclub'


  get :my_books, to: 'pages#my_books'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: %i[index show new create destroy] do
    resources :swaps, only: %i[new create]
    member do
      get :genre
      get :confirmation
    end
  end
  resources :swaps, only: %i[show destroy] do
    member do
      get :chatroom
      get :choose_book
      patch :book_chosen
      patch :reject
      patch :complete
    end
    resources :messages, only: :create
  end
  resources :bookclubs, only: %i[index show] do
    get :confirmation
  end
end

app/views/pages/home.html.erb
<div class="homepage_banner">
  <img src="https://images.unsplash.com/photo-1510172951991-856a654063f9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="books-homepage">
  <div class="flex-right">
    <div class="banner-text">
      <h1>Share the stories</h1>
      <h1>you love.</h1>
    </div>
    <div class="carousel-container">
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <%= image_tag "quote-icon.png",  alt: "Quote icon", id: "quote-image" %>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="carousel-text">
              <h2>All we have to decide is what to do with the time that is given us.</h2>
              <p>– The Fellowship of the Ring</p>
            </div>
          </div>
          <div class="carousel-item">
            <div class="carousel-text">
              <h2>It sounds plausible enough tonight, but wait until tomorrow. Wait for the common sense of the morning.</h2>
              <p>– The Time Machine</p>
            </div>
          </div>
          <div class="carousel-item">
            <div class="carousel-text">
              <h2>And now that you don't have to be perfect, you can be good.</h2>
              <p>– East of Eden</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="banner_btns">
      <%= link_to "Find a Book",  books_path, class: "btn-salmon-outline btn-home" %>
      <%= link_to "Add a Book",  new_book_path, class: "btn-salmon-outline btn-home" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="about_cards row">
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag "find-icon.png",  alt: "Find icon", id: "find-image" %>
        <h2>Find</h2>
        <p>Find a book and request to swap.</p>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag "swap-icon.png",  alt: "Swap icon", id: "swap-image" %>
        <h2>Swap</h2>
        <p>Meet the owner and swap books.</p>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag "book-icon.png",  alt: "Read icon", id: "read-image" %>
        <h2>Read</h2>
        <p>Sit back and enjoy your new book!</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_bookclub.html.erb
<div class="margin-map-show">
  <div class="mapbox-style-show-my-bookclub-show">
    <div class="mapclass-show-my-bookclub-show">
      <div id="map"
         style="width: 100%;
         height: 800px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
       </div>
     </div>
  </div>

</div>
<div class="card-for-map-show">
  <h1><%= @bookclub.name %></h1>
  <img src="https://www.wendywutours.co.uk/blog/wp-content/uploads/2017/11/8booksheader-730x410.jpg" alt="" style="width: 100%;">
  <div class="divider-show mt-2"></div>
  <div class="d-flex w-100 justify-content-between align-items-center mt-4">
    <h2 class='m-0'><%= @bookclub.genre %></h2>
    <p class='m-0'><%= @bookclub.location %></p>
  </div>
  <p class="mt-3"><%= @bookclub.description %></p>
  <p class="mt-3">Capacity: <%= @bookclub.capacity %></p>
  <%= link_to "Change Bookclub", bookclubs_path, class: 'thinging-2-show'%>
</div>
</div>

<div>
   <%= image_tag "logo.png", alt: "alttext", class: 'junto-logo' %>
</div>

app/views/pages/my_books.html.erb
<div class="container my-books-container">

  <div id="my-books-header">
    <h2><%= "My Books" %></h2>
    <% if @books.where(hidden: false).empty? %>
      <p>You haven't listed any books on Junto yet! Why not add one today?</p>
    <% else %>
      <p>Your books are live on Junto and ready to swap!</p>
    <% end %>

    <%= link_to "Add a Book",  new_book_path, class: "btn-salmon mb-10" %>

  </div>


  <div class="cards">
    <% @books.where(hidden: false).each do |book| %>
      <div class="card-book">
        <% if book.photo.attached? %>
          <%= cl_image_tag book.photo.key, class: 'book-cover' %>
        <% else %>
          <%= image_tag "https://i.imgur.com/sJ3CT4V.gif", class: 'book-cover' %>
        <% end %>
          <div class="card-items">
            <h2><%= "#{book.title}" %></h2>
            <p id="author"><%= author_cleaning(book.author_name) %></p>
            <p id="year"><%= book.year %></p>
          </div>
          <div id="avatar-my-books">
            <%= cl_image_tag book.user.photo.key, class: 'card-avatar' %>
          </div>
          <%= link_to "Delete", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-salmon-outline bottom-right" %>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/my_swaps.html.erb
<div class="container">
  <div class="swaps-box">
    <div class="flex-title-swaps">
      <h2 class="swaps-title">My Swaps </h2>
      <%= link_to "Choose another book", books_path, class: "btn-salmon-outline link-to-books" %>
    </div>
    <div class="row">
      <div class="col-12">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
           <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Pending</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Complete</a>
          </li>
        </ul>

        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="pending-swaps">
              <div class="pending-message">
                <% if @swaps.where.not(status: 'complete').empty? %>
                  <p>You have no pending swaps! Choose a book today.</p>
                <% end %>
              </div>


              <% @swaps.each do |swap| %>

                <% if swap.giving_user == current_user && swap.status == 'pending' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">
                      <div class="book-images-1">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <div class="avatar-images-1">
                          <%= cl_image_tag swap.receiving_user.photo.key, class: 'card-avatar receiving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4><%= "New request received from #{swap.receiving_user.first_name.capitalize}" %></h4>
                        <p><%= "Book #{swap.receiving_user.first_name.capitalize} would like: #{swap.book_given.title}, #{swap.book_given.year}" %></p>
                        <p><%= "#{swap.receiving_user.first_name.capitalize}'s Location: #{swap.giving_user.location}" %></p>
                        <p><%= "Choose one of #{swap.receiving_user.first_name.capitalize}'s books or reject the request:" %></p>
                        <div class="swap-buttons">
                          <%= link_to "Choose a Book", choose_book_swap_path(swap), class: "btn-salmon btn-block" %>
                          <%= link_to "Reject Request", reject_swap_path(swap), method: :patch, data: { confirm: 'Are you sure?' }, class: "btn-salmon-outline btn-block" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>


                <% if swap.receiving_user == current_user && swap.status == 'pending' %>
                  <div class="bookswap-card">
                    <div class="d-flex">
                      <div class="book-images-1">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <div class="avatar-images-1">
                          <%= cl_image_tag swap.giving_user.photo.key, class: 'card-avatar giving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4><%= "Request sent to #{swap.giving_user.first_name.capitalize}" %></h4>
                        <p><%= "Book you would like: #{swap.book_given.title}, #{swap.book_given.year}" %></p>
                        <p><%= "#{swap.giving_user.first_name.capitalize}'s Location: #{swap.giving_user.location}" %></p>
                        <p><%= "Waiting for #{swap.giving_user.first_name.capitalize} to approve your request" %></p>
                        <div class="swap-buttons">
                          <%= link_to "Cancel Request", swap_path(swap), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-salmon btn-block" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>


                <% if swap.giving_user == current_user && swap.status == 'bookchosen' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">

                      <div class="book-images-2">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <%= cl_image_tag swap.book_received.photo.key, class: 'book-cover book-cover-swaps receiving-book' %>
                        <div class="avatar-images-2">
                          <%= cl_image_tag swap.giving_user.photo.key, class: 'card-avatar giving-avatar' %>
                          <%= cl_image_tag swap.receiving_user.photo.key, class: 'card-avatar receiving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4><%= "You accepted #{swap.receiving_user.first_name.capitalize}'s request!" %></h4>
                        <p><%= "Book #{swap.receiving_user.first_name.capitalize} would like: #{swap.book_given.title}, #{swap.book_given.year}" %></p>
                        <p><%= "Book you would like: #{swap.book_received.title}, #{swap.book_received.year}" %></p>
                        <p><%= "#{swap.receiving_user.first_name.capitalize}'s Location: #{swap.receiving_user.location}" %></p>
                        <p><%= "Chat with #{swap.receiving_user.first_name.capitalize} to arrange the swap" %></p>
                        <p>Remember to follow the safety guidelines</p>
                        <div class="swap-buttons">
                          <%= link_to "Chat with #{swap.receiving_user.first_name.capitalize}", chatroom_swap_path(swap), class: "btn-salmon btn-block" %>
                          <%= link_to "Mark Swap Complete", complete_swap_path(swap), method: :patch, data: { confirm: 'Are you sure?' }, class: "btn-salmon-outline btn-block" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>


                <% if swap.receiving_user == current_user && swap.status == 'bookchosen' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">
                      <div class="book-images-2">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <%= cl_image_tag swap.book_received.photo.key, class: 'book-cover book-cover-swaps receiving-book' %>
                        <div class="avatar-images-2">
                          <%= cl_image_tag swap.giving_user.photo.key, class: 'card-avatar giving-avatar' %>
                          <%= cl_image_tag swap.receiving_user.photo.key, class: 'card-avatar receiving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4><%= "#{swap.giving_user.first_name.capitalize} accepted your request!" %></h4>
                        <p><%= "Book you would like: #{swap.book_given.title}, #{swap.book_given.year}" %></p>
                        <p><%= "Book #{swap.giving_user.first_name.capitalize} would like: #{swap.book_received.title}, #{swap.book_received.year}" %></p>
                        <p><%= "#{swap.giving_user.first_name.capitalize}'s Location: #{swap.giving_user.location}" %></p>
                        <p><%= "Great news, #{swap.giving_user.first_name.capitalize} has approved your request and chosen one of your books!" %></p>
                        <p><%= "Chat with #{swap.giving_user.first_name.capitalize} to arrange the swap" %></p>
                        <p>Remember to follow the safety guidelines</p>
                        <div class="swap-buttons">
                          <%= link_to "Chat with #{swap.giving_user.first_name.capitalize}", chatroom_swap_path(swap), class: "btn-salmon btn-block" %>
                          <%= link_to "Mark Swap Complete", complete_swap_path(swap), method: :patch, data: { confirm: 'Are you sure?' }, class: "btn-salmon-outline btn-block" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>

              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="complete-swaps">
              <div class="complete-message">
                <% if @swaps.where(status: 'complete').or(@swaps.where(status: 'rejected')).empty? %>
                  <p>You have no completed swaps!</p>
                <% end %>
              </div>

              <% @swaps.each do |swap| %>

                <% if (swap.giving_user == current_user || swap.receiving_user == current_user) && swap.status == 'complete' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">
                      <div class="book-images-2">
                        <%= cl_image_tag swap.book_received.photo.key, class: 'book-cover book-cover-swaps receiving-book' %>
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <div class="avatar-images-2">
                          <%= cl_image_tag swap.receiving_user.photo.key, class: 'card-avatar receiving-avatar' %>
                          <%= cl_image_tag swap.giving_user.photo.key, class: 'card-avatar giving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4>Swap Complete</h4>
                        <p><%= "#{swap.receiving_user.first_name.capitalize} gave: #{swap.book_received.title}, #{swap.book_received.year}" %></p>
                        <p><%= "#{swap.giving_user.first_name.capitalize} gave: #{swap.book_given.title}, #{swap.book_given.year}" %></p>
                      </div>
                    </div>
                  </div>
                <% end %>


                <% if swap.giving_user == current_user && swap.status == 'rejected' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">
                      <div class="book-images-1">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <div class="avatar-images-1">
                          <%= cl_image_tag swap.receiving_user.photo.key, class: 'card-avatar receiving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4>Swap Rejected</h4>
                        <p><%= "We've notified #{swap.receiving_user.first_name.capitalize} that you rejected their request for #{swap.book_given.title}, #{swap.book_given.year}." %></p>
                      </div>
                    </div>
                  </div>
                <% end %>


                <% if swap.receiving_user == current_user && swap.status == 'rejected' %>
                  <div class="bookswap-card d-flex">
                    <div class="d-flex">
                      <div class="book-images-1">
                        <%= cl_image_tag swap.book_given.photo.key, class: 'book-cover book-cover-swaps giving-book' %>
                        <div class="avatar-images-1">
                          <%= cl_image_tag swap.giving_user.photo.key, class: 'card-avatar giving-avatar' %>
                        </div>
                      </div>
                      <div class="bookswap-card-info">
                        <h4>Swap Rejected</h4>
                        <p><%= "Sorry, #{swap.giving_user.first_name.capitalize} rejected your request for #{swap.book_given.title}, #{swap.book_given.year}. Browse for a different book." %></p>
                      </div>
                    </div>
                  </div>
                <% end %>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/replica.html.erb
<div class="container image-background">
  <h1 style="margin-top: 10px;">Share the stories you love.</h1>
</div>
<div class="button_position">
  <%= link_to "Find a Book",  books_path, class: "btn-salmon btn-signup" %>
  <%= link_to "Add a Book",  new_book_path, class: "btn-salmon btn-signup ml-3" %>
</div>

  <br>
  <br>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag("/assets/find-icon.png",  alt: "Find icon", id: "find-image") %>
        <h2>Find</h2>
        <p>Find a book and request to swap.</p>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag("/assets/swap-icon.png",  alt: "Swap icon", id: "swap-image") %>
        <h2>Swap</h2>
        <p>Meet the owner and swap books.</p>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 flex-item">
      <div class="icon-card" style="text-align: left;">
        <%= image_tag("/assets/book-icon.png",  alt: "Read icon", id: "read-image") %>
        <h2>Read</h2>
        <p>Sit back and enjoy your new book!</p>
      </div>
    </div>
  </div>
</div>