config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :my_swaps, to: 'pages#my_swaps'

  get :my_bookclub, to: 'pages#my_bookclub'


  get :my_books, to: 'pages#my_books'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: %i[index show new create destroy] do
    resources :swaps, only: %i[new create]
    member do
      get :genre
      get :confirmation
    end
  end
  resources :swaps, only: %i[show destroy] do
    member do
      get :chatroom
      get :choose_book
      patch :book_chosen
      patch :reject
      patch :complete
    end
    resources :messages, only: :create
  end
  resources :bookclubs, only: %i[index show] do
    get :confirmation
  end
end

app/models/bookclub.rb
class Bookclub < ApplicationRecord

  after_create :add_creator_as_member

  has_many :users, dependent: :destroy
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def add_creator_as_member
    creator.update(bookclub: self)
  end
end

app/controllers/bookclubs_controller.rb
class BookclubsController < ApplicationController
  def show
    @no_footer = true
    @bookclub = Bookclub.find(params[:id])
    @markers = [{
      lat: @bookclub.latitude,
      lng: @bookclub.longitude,
      image_url: helpers.asset_url('map-icon.png')
    }]
    @book = @bookclub.users[0].books[0] || Book.first
  end

  def index
    # @bookclubs = Bookclub.where(genre: params.dig(:search, :genre))
    # @bookclubs = Bookclub.all if @bookclubs.empty)
    if !params[:filter] || params[:filter] == "All"
      @bookclubs = Bookclub.all
    elsif params[:filter].present?
      @bookclubs = Bookclub.where(genre: params[:filter])
    end
  end

  def confirmation
    @bookclub = Bookclub.find(params[:bookclub_id])
    current_user.bookclub = @bookclub
    current_user.save
  end
end

# if params[:query].present?
      # sql_query = "title ILIKE :query OR description ILIKE :query OR genre ILIKE :query"
      # @books = Book.where(sql_query, query: "%#{params[:query]}%")
    # else
      # @books = Book.all
    # end
    # if params[:filter].present?
      # @books = @books.where(genre: params[:filter])
    # end

app/views/bookclubs/confirmation.html.erb
<div class="image-bookclub-confirmation">
  <img src="https://images.unsplash.com/photo-1543497415-75c0a27177c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=882&q=80" alt="">
</div>


<div class="bookclub-confirmation-message">
  <h2>Congratulations! You have joined <%= @bookclub.name %> book club.</h2>
  <p>An email will be sent to you confirming contact details and meetup times!</p>
</div>



</div>
  <%= link_to "Discover your new bookclub",  bookclub_path(@bookclub), class: 'btn-salmon-outline link-button-confirmation'%>
</div>

app/views/bookclubs/index.html.erb
<div class="banner-index">
  <div class="container">
    <div class="row banner-contents">
      <div class="col-lg-12 col-md-8 col-xs-4 align-items-center">
        <div id="header-container-bookclubs">
          <h1>Discover your next book club...</h1>
          <p>Click on a book club to learn more and join</p>
        </div>
      </div>
    </div>

    <div class="filter-bar">
      <h3>Filter</h3>
      <div class="dropdown">
        <button class="btn btn-filter dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= params[:filter].present? ? params[:filter] : 'Genre' %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to 'Fantasy', bookclubs_path(query: params[:query], filter: 'Fantasy'), class: "dropdown-item"  %>
          <%= link_to 'Feminist', bookclubs_path(query: params[:query], filter: 'Feminist'), class: "dropdown-item"  %>
          <%= link_to 'Non-fiction', bookclubs_path(query: params[:query], filter: 'Non-fiction'), class: "dropdown-item"  %>
          <%= link_to 'True Crime', bookclubs_path(query: params[:query], filter: 'True Crime'), class: "dropdown-item"  %>
          <%= link_to 'Thriller', bookclubs_path(query: params[:query], filter: 'Thriller'), class: "dropdown-item"  %>
          <%= link_to 'Classic', bookclubs_path(query: params[:query], filter: 'Classic'), class: "dropdown-item"  %>
          <%= link_to 'Any', bookclubs_path(query: params[:query], filter: 'Any'), class: "dropdown-item"  %>
          <%= link_to 'All', bookclubs_path(query: params[:query], filter: 'All'), class: "dropdown-item"  %>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="bookclub-cards">
    <% @bookclubs.each do |bookclub| %>
      <%= link_to(bookclub_path(bookclub), class: "card-links") do %>
        <div>

          <div class="card-trip">
            <img src=" <%= bookclub.image_url %>", alt="Book Club photos" />
            <div class="card-trip-infos">
              <div class="card-design">
                <div class="bookclub-name-postcode">
                  <h4><%= "#{bookclub.name}" %></h4>
                  <p><%= "#{bookclub.location}" %></p>
                </div>
                <div class="lil-book-genre">
                  <i class="fas fa-book-open"></i>

                  <p><%= "#{bookclub.genre}" %></p>
                </div>
                <p><%= "#{bookclub.description}" %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookclubs/show.html.erb
<div class="whole-flex">
  <div class="whole-card-show">
    <h1 style="width: 400px;"><%= @bookclub.name %></h1>
    <h2><%= @bookclub.location %></h2>
    <div class="margin-map">
      <div class="mapbox-style-show-my-bookclub">
        <div class="mapclass-show-my-bookclub">
          <div id="map"
             style="width: 400px;
             height: 250px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
           </div>
         </div>
      </div>
    </div>
    <img src=" <%= @bookclub.image_url %>", alt="Book Club photos", class="bookclub-owner-image" />
    <% if @bookclub != current_user.bookclub  %>
      <%= link_to "Join Book Club", bookclub_confirmation_path(@bookclub), class: 'wide-width-button', style: 'width: 400px;' %>
    <% else %>
      <%= link_to 'Change my book club', bookclubs_path, class: 'wide-width-button', style: 'width: 400px;'  %>
    <% end %>
    <div class="flex-info">
      <p class="capacity-show">Capacity: <%= "#{@bookclub.capacity}" %></p>
      <% User.all.order(:id)[7..11].each do |user| %>
      <div class="d-flex align-items-start justify-content-start">
        <%= cl_image_tag user.photo.key, alt: "alttext", class: "avatar" %>
        <p class="text-left" style="border-bottom: 1px solid black; margin-bottom: 15px; padding-bottom: 15px; margin-left: 15px; width: 355px;"><%= user.description %></p>
      </div>
      <% end %>
      <%= link_to "Back", bookclubs_path, class: "btn-salmon-outline small-button" %>
    </div>
  </div>
  <div class="other">
    <div class="badge-show" style="text-align: center;">Book of the month...</div>
       <%= render "books/book-3d" %>
  </div>
</div>