config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :my_swaps, to: 'pages#my_swaps'

  get :my_bookclub, to: 'pages#my_bookclub'


  get :my_books, to: 'pages#my_books'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: %i[index show new create destroy] do
    resources :swaps, only: %i[new create]
    member do
      get :genre
      get :confirmation
    end
  end
  resources :swaps, only: %i[show destroy] do
    member do
      get :chatroom
      get :choose_book
      patch :book_chosen
      patch :reject
      patch :complete
    end
    resources :messages, only: :create
  end
  resources :bookclubs, only: %i[index show] do
    get :confirmation
  end
end

app/models/swap.rb
class Swap < ApplicationRecord
  belongs_to :book_given, class_name: "Book", foreign_key: 'book_1_id'
  belongs_to :book_received, class_name: "Book", foreign_key: 'book_2_id', optional: true
  belongs_to :giving_user, class_name: "User", foreign_key: 'user_id'
  belongs_to :receiving_user, class_name: "User", foreign_key: 'user_2_id'
  has_many :messages
end

app/controllers/swaps_controller.rb
class SwapsController < ApplicationController


  def create
    @book = Book.find(params[:book_id])
    @book.update(hidden: true)
    @swap = Swap.new(book_given: @book, giving_user: @book.user, receiving_user: current_user)
    @swap.save
    redirect_to swap_path(@swap)
  end

  def show
    @swap = Swap.find(params[:id])
    @book_given = @swap.book_given
  end

  def reject
    @swap = Swap.find(params[:id])
    @swap.update(status: 'rejected')
    @book = @swap.book_given
    @book.update(hidden: false)
    flash[:notice] = 'Swap successfully rejected'
    redirect_to my_swaps_path
  end

  def complete
    @swap = Swap.find(params[:id])
    @swap.update(status: 'complete')
    flash[:notice] = 'Swap marked as complete'
    redirect_to my_swaps_path
  end

  def choose_book
    @swap = Swap.find(params[:id])
    @user = @swap.receiving_user
    @books = @user.books
  end

  def book_chosen
    @swap = Swap.find(params[:id])
    @book = Book.find(params[:book_id])
    @swap.book_received = @book
    @book.update(hidden: true)
    @swap.update(status: 'bookchosen')
    redirect_to my_swaps_path
  end

  def destroy
    @swap = Swap.find(params[:id])
    @book = @swap.book_given
    @book.update(hidden: false)
    @swap.destroy
    flash[:notice] = 'Swap request cancelled'
    redirect_to my_swaps_path
  end

  def chatroom
    # add if/else that only displays chatroom if user is part of the associated swap
    @swap = Swap.find(params[:id])
    @other_user = [@swap.giving_user, @swap.receiving_user].reject { |user| user == current_user}.first
    if current_user == @swap.giving_user || @swap.receiving_user
      @message = Message.new
    else
      redirect_to root_path
    end
  end
end

app/views/swaps/chatroom.html.erb
<div class="all-messages-container">
  <div class="message-recipient ">
    <%= cl_image_tag @other_user.photo.key, alt: "alttext", class: "message-avatar" %>
    <p class="m-0 ml-3"><%= @other_user.first_name + " " + @other_user.last_name %></p>
  </div>
  <div id="messages" data-chatroom-id="<%= @swap.id %>">
    <% @swap.messages.each do |message| %>
      <div class="message-container <%= message.user_id == current_user.id ? 'my-message' : 'their-message' %>">
        <p><%= message.content %></p>
        <i class="author">
          <small class="time-right"><%= message.created_at.strftime("%H:%M") %></small>
        </i>
      </div>
    <% end %>
  </div>
  <div class="message-box">
    <%= simple_form_for [ @swap, @message ], url: swap_messages_path(swap_id: @swap.id), remote: true do |f| %>
      <%= f.input :content, label: false, placeholder: "Message", class: "type-space-message", input_html: { autocomplete: "off" }  %>
      <%= f.submit class: "btn-salmon btn-send", value: "Send" %>
    <% end %>
  </div>
  <%= link_to "Back to my swaps",  my_swaps_path, class: "btn-salmon-outline btn-back" %>
</div>

app/views/swaps/choose_book.html.erb
<div class="container choose-book-container">

  <div id="choose-book-header">
    <h2><%= "#{@user.first_name}'s Books" %></h2>

    <p>Choose a book to complete the switch!</p>

    <%= link_to "Back to My Swaps",  new_book_path, class: "btn-salmon" %>

  </div>

  <div class="cards">
    <% @books.where(:hidden => false).each do |book| %>
      <div class="card-book">
        <% if book.photo.attached? %>
          <%= cl_image_tag book.photo.key, class: 'book-cover' %>
        <% else %>
          <%= image_tag "https://i.imgur.com/sJ3CT4V.gif", class: 'book-cover' %>
        <% end %>
          <div class="card-items">
            <h2><%= "#{book.title}" %></h2>
            <p id="author"><%= author_cleaning(book.author_name) %></p>
            <p id="year"><%= book.year %></p>
          </div>
          <div id="avatar-choose-book">
            <%= cl_image_tag book.user.photo.key, class: 'card-avatar' %>
          </div>
          <%= link_to "Choose", book_chosen_swap_path(@swap, book_id: book.id), method: :patch, class: "btn-salmon-outline bottom-right" %>
      </div>
    <% end %>
  </div>

</div>

app/views/swaps/show.html.erb
<div class="image-show-confirmation">
  <img src="https://images.unsplash.com/photo-1537495329792-41ae41ad3bf0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="#">
</div>


<div class="info-show-confirmation">
  <h2>“If you only read the books that everyone else is reading, you can only think what everyone else is thinking.”</h2>
  <p><em>Haruki Murakami</em></p>
</div>


<div class="info-show-content">
  <h2 style="text-align: center;">Congratulations</h2>
  <br>
  <p style="text-align: center;"><%="Your book request has been sent to #{@swap.giving_user.first_name.capitalize}!"%></p>

  <div class="card-product-show">
    <%= cl_image_tag @book_given.photo.key, class: 'book-image' %>
    <div class="card-product-infos-show">
      <h3><%= @book_given.title %></h3>
      <p><%= @book_given.year %></p>
      <p><%= @book_given.genre %></p>
    </div>
  </div>
    <br>
    <p style="text-align: center;"><%="You will be notified when #{@swap.giving_user.first_name.capitalize} accepts your request!"%></p>
    <%= link_to "My Swaps", my_swaps_path, class: 'btn-salmon btn-block' %>
</div>